### ISSUE TITLE
BUG: Use more than one RDF value as input parameter for my user defined functionF

### ISSUE THREAD

**Issue by KappaGi** [morph-kgc/morph-kgc#187]
####  What Happens?
I can't pass more than one RDF value for an input parameter of my user defined function

#### To Reproduce
Let's suppose I want to pass two or more values `ex:value_1` and `ex:value_2` for input parameter `grel:myParameter` using RDF. None of the following mappings work:

1. Following only returns ex:value_2

```
<#Execution>
    fnml:function ex:myFunction;
    fnml:input
    [
      fnml:parameter grel:param;
      fnml:valueMap [
        rml:reference "column_1";
      ]
    ];
    fnml:input
    [
      fnml:parameter grel:myParameter;
      fnml:value ex:value_1, ex:value_2;
    ];
.
```

2. Following only returns ex:value_2
```
<#Execution>
    fnml:function ex:myFunction;
    fnml:input
    [
      fnml:parameter grel:param;
      fnml:valueMap [
        rml:reference "column_1";
      ]
    ];
    fnml:input
    [
      fnml:parameter grel:myParameter;
      fnml:value ex:value_1;
      fnml:value ex:value_2;
    ];
.
```

3. Following returns a python str object that is not legible
```
<#Execution>
    fnml:function ex:myFunction;
    fnml:input
    [
      fnml:parameter grel:param;
      fnml:valueMap [
        rml:reference "column_1";
      ]
    ];
    fnml:input
    [
      fnml:parameter grel:myParameter;
      fnml:value (ex:value_1 ex:value_2);
    ];
.
```
Thanks for your support.

#### Environment:
 - OS: Ubuntu 22.04 LTS
 - Python version: 3.8
 - Morph-KGC version: 2.6.2

**Comment by arenas-guerrero-julian** [comment]
Hi @KappaGi ,

I am not sure if I understood well since you are missing a complete example with the full mapping, data and udf. I think what you are trying to do is not possible. You could maybe try:

```ttl
<#Execution>
    fnml:function ex:myFunction;
    fnml:input
    [
      fnml:parameter grel:param;
      fnml:valueMap [
        rml:reference "column_1";
      ]
    ];
    fnml:input
    [
      fnml:parameter grel:myParameter;
      fnml:value "ex:value_1 ex:value_2";
    ];
.
```

And manage the multiple values of the parameter within the udf. This is, you can provide the multiple parameters as a character-separated literal (e.g., comma or a whitespace), that in the udf (by splitting...).

**Comment by KappaGi** [comment]
Hello @arenas-guerrero-julian,

Thank you for your answer. I want to have several `fnml:value`s for `grel:myParameter` in my mappings so that in my udf in python I can manage those values as a python list. It works if I use an rdf resource or an rdf literal as `fnml:value`, but It seems that I can't use several rdf resources (nor literals) in the mappings for this purpose.

So the only current solution to have a list of values for a single parameter in python udf is to provide several values in a single literal (i.e. using a delimeter) in the mappings and do the required post-processing in the udf.

**Comment by KappaGi** [comment]
@arenas-guerrero-julian 

Would it be possible to modify the way udf's are defined to accept several rdf resources for a a single parameter? Could you please refer to any piece of code that I can modify to such purpose?

Thanks for the support

**Comment by arenas-guerrero-julian** [comment]
Maybe this corner case is a limitation of [RML-FNML](https://kg-construct.github.io/rml-fnml/spec/docs/), since the current specification does not consider it. I am not sure if what you are trying to achieve is feasible, but function execution is handled [here](https://github.com/morph-kgc/morph-kgc/blob/main/src/morph_kgc/fnml/fnml_executer.py) and probably the parser would need to be modified aswell.

In the workaround that I mentioned, you could provide your list in Python style as input, for instance [1, 2] or ['one', 'two'] and cast the list at the beginning of the function `input_parm = list(input_parm)`.
