### ISSUE TITLE
Issue generating triples with json file

### ISSUE THREAD

**Issue by TereLaguinge** [morph-kgc/morph-kgc#207]
Hi! 

I'm having issues generating certain triples with a json file. I'm using this json file _test_file.txt_ (I changed it to txt to upload it in the comment) and the mapping file _mapping_file_test_ . 

I want to get the connection between word and datasource. Do you know if there's something missing?

Thanks a lot for your help!!

[test_file.txt](https://github.com/morph-kgc/morph-kgc/files/13753518/test_file.txt)
[mapping_file_test.txt](https://github.com/morph-kgc/morph-kgc/files/13753565/mapping_file_test.txt)

**Comment by arenas-guerrero-julian** [comment]
Hi @TereLaguinge ,

The problem comes from the jsonpath expression in your mapping. Unfortunately, the jsonpath library currently used by morph-kgc is not that reliable.

An alternative could be to convert your JSON file to XML (for instance using https://github.com/vinitkumar/json2xml) and use XPath instead (see also #137).

**Comment by TereLaguinge** [comment]
Ok Thank you! Will try that

**Comment by arenas-guerrero-julian** [comment]
Hi @TereLaguinge ,

Did the solution work?
