### ISSUE TITLE
Mapping statistics

### ISSUE THREAD

**Issue by neobernad** [morph-kgc/morph-kgc#272]
Hi,

I was wondering whether it is possible to generate a set of statistics regarding the mapping process. For instance, including the number of times a rule is executed and the duration taken by each set of rules.

Best,
José Antonio

**Comment by arenas-guerrero-julian** [comment]
Hola @neobernad ,

Simple statistics can be logged with `logging_level: DEBUG`. You obtain the number of triples that a rule generates and its excution time. However, because of mapping normalization applied before materialization, the names of the rules are changed and it might be not possible to link them to the name of the original triples maps in your mapping.

An example of the log:

```

**Comment by neobernad** [comment]
Thanks @arenas-guerrero-julian,

Not knowing the actual mapping name might be an issue. But thanks for answering that quickly :-).
